version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booklover
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "0:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./API
      dockerfile: dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/booklover
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  postgres_data:
